/*
 * Copyright (C) 2024 optyfr This program is free software; you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any
 * later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should
 * have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
package jrm.security;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Map;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

import org.apache.fory.ThreadSafeFory;

import jrm.batch.DirUpdaterResults;
import jrm.batch.TrntChkReport;
import jrm.profile.Profile;
import jrm.profile.manager.ProfileNFO;
import jrm.profile.report.Report;

/**
 * Serializes and deserializes application objects with an HMAC integrity envelope.
 * <p>
 * New writes always produce a signed Fory payload:
 * </p>
 * <pre>
 * magic "JRMH" | version 2 (1 byte) | hmacLen (4 BE) | hmac | Fory native bytes
 * </pre>
 * <p>
 * Loads accept only signed {@code JRMH} version-2 envelopes whose HMAC verifies with the per-user random key
 * from {@link CacheIntegrityKey}. Bare Java streams ({@code 0xACED}), JRMH v1, and legacy work-path HMAC
 * envelopes are rejected; those caches are regenerated by a normal load/save cycle.
 * </p>
 */
public final class SignedObjectStore {

    /**
     * Selects the Fory instance (registration list + depth) used for a payload.
     */
    public enum Codec {
        /** Profile, ProfileNFO, and DirScan container maps. Depth 100. */
        CACHE,
        /** Report and DirUpdaterResults. Depth 100. Embeds profile-data types. */
        REPORT,
        /** TrntChkReport piece trees. Depth 1_000_000. */
        TRNTCHK
    }

    private static final byte[] MAGIC = { 'J', 'R', 'M', 'H' };
    private static final byte VERSION = 2;
    /** Java serialization stream header magic ({@code STREAM_MAGIC}). */
    private static final int JAVA_STREAM_MAGIC = 0xACED;

    private SignedObjectStore() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Serializes {@code object} and writes it to {@code file} under a session-bound HMAC envelope.
     * The codec is inferred from the runtime type.
     *
     * @param session the active user session (HMAC key is a per-user random secret)
     * @param file destination file
     * @param object object to serialize
     * @throws IOException if writing fails
     */
    public static void write(final Session session, final File file, final Object object) throws IOException {
        write(session, file, object, inferCodec(object));
    }

    /**
     * Serializes {@code object} with an explicit codec and writes it to {@code file}.
     *
     * @param session the active user session
     * @param file destination file
     * @param object object to serialize
     * @param codec Fory registration/depth instance
     * @throws IOException if writing fails
     */
    public static void write(final Session session, final File file, final Object object, final Codec codec) throws IOException {
        final var serialized = serialize(object, codec);
        final var hmac = computeHmac(session, serialized);
        try (final var fos = new FileOutputStream(file);
                final var bos = new BufferedOutputStream(fos)) {
            bos.write(MAGIC);
            bos.write(VERSION);
            writeInt(bos, hmac.length);
            bos.write(hmac);
            bos.write(serialized);
        }
    }

    /**
     * Reads and deserializes an object from {@code file} using {@link Codec#CACHE}.
     *
     * @param session the active user session
     * @param file source file
     * @return the deserialized object
     * @throws IOException if reading or verification fails
     */
    public static Object read(final Session session, final File file) throws IOException {
        return read(session, file, Codec.CACHE);
    }

    /**
     * Reads and deserializes an object from {@code file} with the given codec.
     *
     * @param session the active user session
     * @param file source file
     * @param codec Fory registration/depth instance
     * @return the deserialized object
     * @throws IOException if reading or verification fails
     */
    public static Object read(final Session session, final File file, final Codec codec) throws IOException {
        return readBytes(session, Files.readAllBytes(file.toPath()), codec);
    }

    /**
     * Reads all bytes from {@code in} (up to {@code length} when positive) and deserializes with {@link Codec#CACHE}.
     *
     * @param session the active user session
     * @param in source stream
     * @param length expected length, or {@code -1} to read until EOF
     * @return the deserialized object
     * @throws IOException if reading or verification fails
     */
    public static Object read(final Session session, final InputStream in, final int length) throws IOException {
        return read(session, in, length, Codec.CACHE);
    }

    /**
     * Reads all bytes from {@code in} with the given codec.
     *
     * @param session the active user session
     * @param in source stream
     * @param length expected length, or {@code -1} to read until EOF
     * @param codec Fory registration/depth instance
     * @return the deserialized object
     * @throws IOException if reading or verification fails
     */
    public static Object read(final Session session, final InputStream in, final int length, final Codec codec) throws IOException {
        final byte[] bytes;
        if (length > 0) {
            bytes = in.readNBytes(length);
        } else {
            bytes = in.readAllBytes();
        }
        return readBytes(session, bytes, codec);
    }

    /**
     * Deserializes from an in-memory payload. Only signed {@code JRMH} version-2 envelopes are accepted.
     *
     * @param session the active user session
     * @param fileBytes full file contents
     * @param codec Fory registration/depth instance
     * @return the deserialized object
     * @throws IOException if reading or verification fails
     */
    public static Object readBytes(final Session session, final byte[] fileBytes, final Codec codec) throws IOException {
        if (fileBytes == null || fileBytes.length < 2) {
            throw new IOException("Serialized payload too short");
        }
        if (hasMagic(fileBytes)) {
            return readSigned(session, fileBytes, codec);
        }
        if (isJavaStream(fileBytes)) {
            throw new SecurityException("Unsigned Java serialization stream rejected");
        }
        throw new SecurityException("Legacy unsigned or work-path HMAC payload rejected");
    }

    private static Object readSigned(final Session session, final byte[] fileBytes, final Codec codec) throws IOException {
        if (fileBytes.length < MAGIC.length + 1 + 4) {
            throw new IOException("Signed payload header too short");
        }
        final int version = fileBytes[MAGIC.length] & 0xFF;
        if (version != VERSION) {
            throw new IOException("Unsupported signed payload version: " + version);
        }
        final int hmacLength = readInt(fileBytes, MAGIC.length + 1);
        final int dataOffset = MAGIC.length + 1 + 4 + hmacLength;
        if (hmacLength <= 0 || dataOffset > fileBytes.length) {
            throw new IOException("Invalid signed payload header");
        }
        final var expectedHmac = Arrays.copyOfRange(fileBytes, MAGIC.length + 1 + 4, dataOffset);
        final var serialized = Arrays.copyOfRange(fileBytes, dataOffset, fileBytes.length);
        verifyHmac(session, serialized, expectedHmac);
        return deserialize(serialized, codec);
    }

    private static Object deserialize(final byte[] serialized, final Codec codec) {
        final var effective = codec == null ? Codec.CACHE : codec;
        final ThreadSafeFory fory = ForyPersistence.get(effective);
        final Object root = fory.deserialize(serialized);
        afterLoad(root);
        return root;
    }

    private static byte[] serialize(final Object object, final Codec codec) {
        return ForyPersistence.get(codec).serialize(object);
    }

    private static void afterLoad(final Object root) {
        if (root instanceof Profile profile) {
            profile.afterLoad();
        } else if (root instanceof Report report) {
            report.afterLoad();
        } else if (root instanceof TrntChkReport report) {
            report.afterLoad();
        }
    }

    private static Codec inferCodec(final Object object) {
        if (object instanceof Profile || object instanceof ProfileNFO || object instanceof Map) {
            return Codec.CACHE;
        }
        if (object instanceof Report || object instanceof DirUpdaterResults) {
            return Codec.REPORT;
        }
        if (object instanceof TrntChkReport) {
            return Codec.TRNTCHK;
        }
        return Codec.CACHE;
    }

    private static void verifyHmac(final Session session, final byte[] data, final byte[] expectedHmac) {
        final var actualHmac = computeHmac(session, data);
        if (!MessageDigest.isEqual(expectedHmac, actualHmac)) {
            throw new SecurityException("Serialized object integrity check failed");
        }
    }

    private static byte[] computeHmac(final Session session, final byte[] data) {
        try {
            final var mac = Mac.getInstance(CacheIntegrityKey.HMAC_ALGORITHM);
            mac.init(getHmacKey(session));
            return mac.doFinal(data);
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new IllegalStateException("HMAC computation failed", e);
        }
    }

    private static SecretKeySpec getHmacKey(final Session session) {
        return CacheIntegrityKey.get(session);
    }

    private static boolean hasMagic(final byte[] bytes) {
        if (bytes.length < MAGIC.length) {
            return false;
        }
        for (int i = 0; i < MAGIC.length; i++) {
            if (bytes[i] != MAGIC[i]) {
                return false;
            }
        }
        return true;
    }

    private static boolean isJavaStream(final byte[] bytes) {
        return bytes.length >= 2 && ((bytes[0] & 0xFF) << 8 | (bytes[1] & 0xFF)) == JAVA_STREAM_MAGIC;
    }

    private static int readInt(final byte[] bytes, final int offset) {
        return ((bytes[offset] & 0xFF) << 24)
                | ((bytes[offset + 1] & 0xFF) << 16)
                | ((bytes[offset + 2] & 0xFF) << 8)
                | (bytes[offset + 3] & 0xFF);
    }

    private static void writeInt(final BufferedOutputStream out, final int value) throws IOException {
        out.write((value >> 24) & 0xFF);
        out.write((value >> 16) & 0xFF);
        out.write((value >> 8) & 0xFF);
        out.write(value & 0xFF);
    }
}
